// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package repository

import (
	"database/sql"
	"time"
)

type ArrService struct {
	ID                  string
	Type                string
	Name                string
	BaseUrl             string
	ApiKey              string
	QualityProfile      string
	RootFolderPath      string
	MinimumAvailability string
	Is4k                bool
	CreatedAt           sql.NullTime
}

type Download struct {
	ID            string
	Title         string
	TorrentTitle  string
	Source        string
	TmdbID        sql.NullInt64
	TvdbID        sql.NullInt64
	Hash          sql.NullString
	Progress      sql.NullFloat64
	TimeLeft      sql.NullString
	Status        sql.NullString
	LastUpdated   sql.NullTime
	DownloadSpeed sql.NullInt64
	UploadSpeed   sql.NullInt64
	DownloadSize  sql.NullInt64
}

type DownloadClient struct {
	ID        string
	Type      string
	Name      string
	Host      string
	Port      int64
	Username  sql.NullString
	Password  sql.NullString
	ApiKey    sql.NullString
	UseSsl    sql.NullBool
	CreatedAt sql.NullTime
}

type LibraryItem struct {
	ID                     string
	Name                   string
	OriginalTitle          sql.NullString
	Type                   string
	ParentID               sql.NullString
	SeriesID               sql.NullString
	SeasonNumber           sql.NullInt64
	EpisodeNumber          sql.NullInt64
	Year                   sql.NullInt64
	PremiereDate           sql.NullString
	EndDate                sql.NullString
	CommunityRating        sql.NullFloat64
	CriticRating           sql.NullFloat64
	OfficialRating         sql.NullString
	Overview               sql.NullString
	Tagline                sql.NullString
	Genres                 sql.NullString
	Studios                sql.NullString
	People                 sql.NullString
	TmdbID                 sql.NullString
	ImdbID                 sql.NullString
	TvdbID                 sql.NullString
	MusicbrainzID          sql.NullString
	Path                   sql.NullString
	Container              sql.NullString
	SizeBytes              sql.NullInt64
	Bitrate                sql.NullInt64
	Width                  sql.NullInt64
	Height                 sql.NullInt64
	AspectRatio            sql.NullString
	VideoCodec             sql.NullString
	AudioCodec             sql.NullString
	SubtitleTracks         sql.NullString
	AudioTracks            sql.NullString
	RuntimeTicks           sql.NullInt64
	RuntimeMinutes         sql.NullInt64
	IsFolder               sql.NullBool
	IsResumable            sql.NullBool
	PlayCount              sql.NullInt64
	DateCreated            sql.NullString
	DateModified           sql.NullString
	LastPlayedDate         sql.NullString
	UserData               sql.NullString
	ChapterImagesExtracted sql.NullBool
	PrimaryImageTag        sql.NullString
	BackdropImageTags      sql.NullString
	LogoImageTag           sql.NullString
	ArtImageTag            sql.NullString
	ThumbImageTag          sql.NullString
	IsHd                   sql.NullBool
	Is4k                   sql.NullBool
	Is3d                   sql.NullBool
	Locked                 sql.NullBool
	ProviderIds            sql.NullString
	ExternalUrls           sql.NullString
	Tags                   sql.NullString
	SortName               sql.NullString
	ForcedSortName         sql.NullString
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type MountedDrife struct {
	ID              string
	Name            string
	MountPath       string
	Filesystem      sql.NullString
	TotalSize       sql.NullInt64
	UsedSize        sql.NullInt64
	AvailableSize   sql.NullInt64
	UsagePercentage sql.NullFloat64
	IsOnline        sql.NullBool
	LastChecked     sql.NullTime
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type Permission struct {
	ID          string
	Name        string
	Description sql.NullString
}

type Request struct {
	ID          int64
	UserID      string
	MediaType   string
	TmdbID      sql.NullInt64
	Title       sql.NullString
	Status      string
	Notes       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	FulfilledAt sql.NullTime
	ApproverID  sql.NullString
	OnBehalfOf  sql.NullString
	PosterUrl   sql.NullString
}

type ServiceStatus struct {
	Name        string
	Online      sql.NullBool
	LastChecked sql.NullTime
}

type Setting struct {
	Key   string
	Value string
}

type TmdbApiUsage struct {
	ID           int64
	Endpoint     string
	RequestCount sql.NullInt64
	Date         time.Time
	CreatedAt    sql.NullTime
}

type TmdbCache struct {
	CacheKey  string
	Data      string
	Endpoint  string
	ExpiresAt time.Time
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type TmdbStaticDatum struct {
	DataType    string
	Data        string
	LastUpdated sql.NullTime
}

type User struct {
	ID           string
	Username     string
	AccessToken  sql.NullString
	AvatarUrl    sql.NullString
	Email        sql.NullString
	UserType     string
	PasswordHash sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type UserPermission struct {
	UserID       string
	PermissionID string
}

type UserSetting struct {
	UserID    string
	Key       string
	Value     string
	UpdatedAt sql.NullTime
}
