// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package repository

import (
	"database/sql"
	"time"
)

type ArrService struct {
	ID                  string
	Type                string
	Name                string
	BaseUrl             string
	ApiKey              string
	QualityProfile      string
	RootFolderPath      string
	MinimumAvailability string
	CreatedAt           sql.NullTime
}

type Download struct {
	ID           string
	Title        string
	TorrentTitle string
	Source       string
	TmdbID       sql.NullInt64
	TvdbID       sql.NullInt64
	Hash         sql.NullString
	Progress     sql.NullFloat64
	TimeLeft     sql.NullString
	Status       sql.NullString
	LastUpdated  sql.NullTime
}

type DownloadClient struct {
	ID        string
	UserID    string
	Type      string
	Name      string
	Host      string
	Port      int64
	Username  sql.NullString
	Password  sql.NullString
	ApiKey    sql.NullString
	UseSsl    sql.NullBool
	CreatedAt sql.NullTime
}

type EmbyMediaItem struct {
	ID           string
	Name         string
	Type         string
	Year         sql.NullInt64
	TmdbID       sql.NullString
	ImdbID       sql.NullString
	TvdbID       sql.NullString
	Path         sql.NullString
	RuntimeTicks sql.NullInt64
	UpdatedAt    time.Time
}

type Request struct {
	ID          int64
	UserID      string
	MediaType   string
	TmdbID      sql.NullInt64
	Title       sql.NullString
	Status      string
	Notes       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	FulfilledAt sql.NullTime
	ApproverID  sql.NullString
	OnBehalfOf  sql.NullString
	PosterUrl   sql.NullString
}

type ServiceStatus struct {
	Name        string
	Online      sql.NullBool
	LastChecked sql.NullTime
}

type Setting struct {
	Key   string
	Value string
}

type User struct {
	ID          string
	Username    string
	AccessToken sql.NullString
	Email       sql.NullString
}

type UserSetting struct {
	UserID    string
	Key       string
	Value     string
	UpdatedAt sql.NullTime
}
