// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: mounted_drives.sql

package repository

import (
	"context"
	"database/sql"
)

const createMountedDrive = `-- name: CreateMountedDrive :exec
INSERT INTO mounted_drives (
    id, name, mount_path, filesystem, total_size, used_size, 
    available_size, usage_percentage, is_online, last_checked
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateMountedDriveParams struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	MountPath       string          `json:"mount_path"`
	Filesystem      sql.NullString  `json:"filesystem"`
	TotalSize       sql.NullInt64   `json:"total_size"`
	UsedSize        sql.NullInt64   `json:"used_size"`
	AvailableSize   sql.NullInt64   `json:"available_size"`
	UsagePercentage sql.NullFloat64 `json:"usage_percentage"`
	IsOnline        sql.NullBool    `json:"is_online"`
	LastChecked     sql.NullTime    `json:"last_checked"`
}

func (q *Queries) CreateMountedDrive(ctx context.Context, arg CreateMountedDriveParams) error {
	_, err := q.db.ExecContext(ctx, createMountedDrive,
		arg.ID,
		arg.Name,
		arg.MountPath,
		arg.Filesystem,
		arg.TotalSize,
		arg.UsedSize,
		arg.AvailableSize,
		arg.UsagePercentage,
		arg.IsOnline,
		arg.LastChecked,
	)
	return err
}

const deleteMountedDrive = `-- name: DeleteMountedDrive :exec
DELETE FROM mounted_drives WHERE id = ?
`

func (q *Queries) DeleteMountedDrive(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMountedDrive, id)
	return err
}

const getAllMountedDrives = `-- name: GetAllMountedDrives :many
SELECT id, name, mount_path, filesystem, total_size, used_size, available_size, usage_percentage, is_online, monitoring_enabled, warning_threshold, critical_threshold, growth_rate_threshold, last_checked, created_at, updated_at FROM mounted_drives ORDER BY name
`

func (q *Queries) GetAllMountedDrives(ctx context.Context) ([]MountedDrife, error) {
	rows, err := q.db.QueryContext(ctx, getAllMountedDrives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MountedDrife
	for rows.Next() {
		var i MountedDrife
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MountPath,
			&i.Filesystem,
			&i.TotalSize,
			&i.UsedSize,
			&i.AvailableSize,
			&i.UsagePercentage,
			&i.IsOnline,
			&i.MonitoringEnabled,
			&i.WarningThreshold,
			&i.CriticalThreshold,
			&i.GrowthRateThreshold,
			&i.LastChecked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMountedDrive = `-- name: GetMountedDrive :one
SELECT id, name, mount_path, filesystem, total_size, used_size, available_size, usage_percentage, is_online, monitoring_enabled, warning_threshold, critical_threshold, growth_rate_threshold, last_checked, created_at, updated_at FROM mounted_drives WHERE id = ?
`

func (q *Queries) GetMountedDrive(ctx context.Context, id string) (MountedDrife, error) {
	row := q.db.QueryRowContext(ctx, getMountedDrive, id)
	var i MountedDrife
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MountPath,
		&i.Filesystem,
		&i.TotalSize,
		&i.UsedSize,
		&i.AvailableSize,
		&i.UsagePercentage,
		&i.IsOnline,
		&i.MonitoringEnabled,
		&i.WarningThreshold,
		&i.CriticalThreshold,
		&i.GrowthRateThreshold,
		&i.LastChecked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMountedDriveByPath = `-- name: GetMountedDriveByPath :one
SELECT id, name, mount_path, filesystem, total_size, used_size, available_size, usage_percentage, is_online, monitoring_enabled, warning_threshold, critical_threshold, growth_rate_threshold, last_checked, created_at, updated_at FROM mounted_drives WHERE mount_path = ?
`

func (q *Queries) GetMountedDriveByPath(ctx context.Context, mountPath string) (MountedDrife, error) {
	row := q.db.QueryRowContext(ctx, getMountedDriveByPath, mountPath)
	var i MountedDrife
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MountPath,
		&i.Filesystem,
		&i.TotalSize,
		&i.UsedSize,
		&i.AvailableSize,
		&i.UsagePercentage,
		&i.IsOnline,
		&i.MonitoringEnabled,
		&i.WarningThreshold,
		&i.CriticalThreshold,
		&i.GrowthRateThreshold,
		&i.LastChecked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMountedDrivesForPolling = `-- name: GetMountedDrivesForPolling :many
SELECT id, name, mount_path, filesystem, total_size, used_size, available_size, usage_percentage, is_online, monitoring_enabled, warning_threshold, critical_threshold, growth_rate_threshold, last_checked, created_at, updated_at FROM mounted_drives WHERE is_online = TRUE
`

func (q *Queries) GetMountedDrivesForPolling(ctx context.Context) ([]MountedDrife, error) {
	rows, err := q.db.QueryContext(ctx, getMountedDrivesForPolling)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MountedDrife
	for rows.Next() {
		var i MountedDrife
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MountPath,
			&i.Filesystem,
			&i.TotalSize,
			&i.UsedSize,
			&i.AvailableSize,
			&i.UsagePercentage,
			&i.IsOnline,
			&i.MonitoringEnabled,
			&i.WarningThreshold,
			&i.CriticalThreshold,
			&i.GrowthRateThreshold,
			&i.LastChecked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMountedDrives = `-- name: ListMountedDrives :many
SELECT id, name, mount_path, filesystem, total_size, used_size, available_size, usage_percentage, is_online, monitoring_enabled, warning_threshold, critical_threshold, growth_rate_threshold, last_checked, created_at, updated_at FROM mounted_drives ORDER BY name
`

func (q *Queries) ListMountedDrives(ctx context.Context) ([]MountedDrife, error) {
	rows, err := q.db.QueryContext(ctx, listMountedDrives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MountedDrife
	for rows.Next() {
		var i MountedDrife
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MountPath,
			&i.Filesystem,
			&i.TotalSize,
			&i.UsedSize,
			&i.AvailableSize,
			&i.UsagePercentage,
			&i.IsOnline,
			&i.MonitoringEnabled,
			&i.WarningThreshold,
			&i.CriticalThreshold,
			&i.GrowthRateThreshold,
			&i.LastChecked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDriveThresholds = `-- name: UpdateDriveThresholds :exec
UPDATE mounted_drives SET
    warning_threshold = ?,
    critical_threshold = ?,
    growth_rate_threshold = ?,
    monitoring_enabled = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateDriveThresholdsParams struct {
	WarningThreshold    sql.NullFloat64 `json:"warning_threshold"`
	CriticalThreshold   sql.NullFloat64 `json:"critical_threshold"`
	GrowthRateThreshold sql.NullFloat64 `json:"growth_rate_threshold"`
	MonitoringEnabled   sql.NullBool    `json:"monitoring_enabled"`
	ID                  string          `json:"id"`
}

func (q *Queries) UpdateDriveThresholds(ctx context.Context, arg UpdateDriveThresholdsParams) error {
	_, err := q.db.ExecContext(ctx, updateDriveThresholds,
		arg.WarningThreshold,
		arg.CriticalThreshold,
		arg.GrowthRateThreshold,
		arg.MonitoringEnabled,
		arg.ID,
	)
	return err
}

const updateMountedDrive = `-- name: UpdateMountedDrive :exec
UPDATE mounted_drives SET
    name = ?,
    mount_path = ?,
    filesystem = ?,
    total_size = ?,
    used_size = ?,
    available_size = ?,
    usage_percentage = ?,
    is_online = ?,
    last_checked = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateMountedDriveParams struct {
	Name            string          `json:"name"`
	MountPath       string          `json:"mount_path"`
	Filesystem      sql.NullString  `json:"filesystem"`
	TotalSize       sql.NullInt64   `json:"total_size"`
	UsedSize        sql.NullInt64   `json:"used_size"`
	AvailableSize   sql.NullInt64   `json:"available_size"`
	UsagePercentage sql.NullFloat64 `json:"usage_percentage"`
	IsOnline        sql.NullBool    `json:"is_online"`
	LastChecked     sql.NullTime    `json:"last_checked"`
	ID              string          `json:"id"`
}

func (q *Queries) UpdateMountedDrive(ctx context.Context, arg UpdateMountedDriveParams) error {
	_, err := q.db.ExecContext(ctx, updateMountedDrive,
		arg.Name,
		arg.MountPath,
		arg.Filesystem,
		arg.TotalSize,
		arg.UsedSize,
		arg.AvailableSize,
		arg.UsagePercentage,
		arg.IsOnline,
		arg.LastChecked,
		arg.ID,
	)
	return err
}

const updateMountedDriveStats = `-- name: UpdateMountedDriveStats :exec
UPDATE mounted_drives SET
    total_size = ?,
    used_size = ?,
    available_size = ?,
    usage_percentage = ?,
    is_online = ?,
    last_checked = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateMountedDriveStatsParams struct {
	TotalSize       sql.NullInt64   `json:"total_size"`
	UsedSize        sql.NullInt64   `json:"used_size"`
	AvailableSize   sql.NullInt64   `json:"available_size"`
	UsagePercentage sql.NullFloat64 `json:"usage_percentage"`
	IsOnline        sql.NullBool    `json:"is_online"`
	LastChecked     sql.NullTime    `json:"last_checked"`
	ID              string          `json:"id"`
}

func (q *Queries) UpdateMountedDriveStats(ctx context.Context, arg UpdateMountedDriveStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateMountedDriveStats,
		arg.TotalSize,
		arg.UsedSize,
		arg.AvailableSize,
		arg.UsagePercentage,
		arg.IsOnline,
		arg.LastChecked,
		arg.ID,
	)
	return err
}

const updateMountedDriveUsage = `-- name: UpdateMountedDriveUsage :exec
UPDATE mounted_drives 
SET total_size = ?, used_size = ?, available_size = ?, usage_percentage = ?, is_online = ?, last_checked = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateMountedDriveUsageParams struct {
	TotalSize       sql.NullInt64   `json:"total_size"`
	UsedSize        sql.NullInt64   `json:"used_size"`
	AvailableSize   sql.NullInt64   `json:"available_size"`
	UsagePercentage sql.NullFloat64 `json:"usage_percentage"`
	IsOnline        sql.NullBool    `json:"is_online"`
	ID              string          `json:"id"`
}

func (q *Queries) UpdateMountedDriveUsage(ctx context.Context, arg UpdateMountedDriveUsageParams) error {
	_, err := q.db.ExecContext(ctx, updateMountedDriveUsage,
		arg.TotalSize,
		arg.UsedSize,
		arg.AvailableSize,
		arg.UsagePercentage,
		arg.IsOnline,
		arg.ID,
	)
	return err
}
