// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: permissions.sql

package repository

import (
	"context"
	"database/sql"
)

const checkPermissionExists = `-- name: CheckPermissionExists :one
SELECT COUNT(*) > 0 as permission_exists
FROM permissions
WHERE id = ?1
`

func (q *Queries) CheckPermissionExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkPermissionExists, id)
	var permission_exists bool
	err := row.Scan(&permission_exists)
	return permission_exists, err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (id, name, description)
VALUES (?1, ?2, ?3)
RETURNING id, name, description
`

type CreatePermissionParams struct {
	ID          string
	Name        string
	Description sql.NullString
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, createPermission, arg.ID, arg.Name, arg.Description)
	var i Permission
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions
WHERE id = ?1
`

func (q *Queries) DeletePermission(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePermission, id)
	return err
}

const getAllPermissions = `-- name: GetAllPermissions :many
SELECT id, name, description FROM permissions
ORDER BY name
`

func (q *Queries) GetAllPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, getAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermission = `-- name: GetPermission :one
SELECT id, name, description FROM permissions
WHERE id = ?1
`

func (q *Queries) GetPermission(ctx context.Context, id string) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermission, id)
	var i Permission
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getPermissionByName = `-- name: GetPermissionByName :one
SELECT id, name, description FROM permissions
WHERE name = ?1
`

func (q *Queries) GetPermissionByName(ctx context.Context, name string) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByName, name)
	var i Permission
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE permissions
SET name = ?1,
    description = ?2
WHERE id = ?3
RETURNING id, name, description
`

type UpdatePermissionParams struct {
	Name        string
	Description sql.NullString
	ID          string
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, updatePermission, arg.Name, arg.Description, arg.ID)
	var i Permission
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
